# Generated by Django 5.0.2 on 2024-03-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
