# Generated by Django 5.0.2 on 2024-03-13 18:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_requestsitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestsitems',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
