# Generated by Django 5.0.2 on 2024-03-13 18:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_requestsitems_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
