# Generated by Django 5.0.2 on 2024-03-08 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_items_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
