# Generated by Django 5.0.2 on 2024-03-13 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_items_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
