# Generated by Django 5.0.2 on 2024-03-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_alter_items_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='updated_at',
            field=models.TimeField(default=11),
            preserve_default=False,
        ),
    ]
