# Generated by Django 5.0.2 on 2024-03-15 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_remove_items_image'),
        ('items', '0006_items_is_approved'),
    ]

    operations = [
    ]
