# Generated by Django 5.0.2 on 2024-03-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_merge_0003_remove_items_image_0006_items_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
