# Generated by Django 5.0.2 on 2024-03-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_alter_items_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_type',
            field=models.CharField(choices=[('New', 'New'), ('Like New', 'Like New'), ('Good', 'Good'), ('Fair', 'Fair'), ('Acceptable', 'Acceptable'), ('Well-loved', 'Well-loved'), ('Damaged', 'Damaged'), ('Broken', 'Brokens')], max_length=20, null=True),
        ),
    ]
