# Generated by Django 5.0.2 on 2024-03-16 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_alter_items_item_type'),
        ('items', '0008_items_image'),
    ]

    operations = [
    ]
