# Generated by Django 5.0.2 on 2024-03-09 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_remove_items_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='updated_at',
            field=models.TimeField(default=datetime.date(2024, 3, 9)),
        ),
    ]
