# Generated by Django 5.0.2 on 2024-03-09 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_items_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='updated_at',
        ),
    ]
