# Generated by Django 5.0.2 on 2024-03-25 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
