# Generated by Django 5.0.2 on 2024-03-26 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report_resolved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='read',
        ),
    ]
